### ISSUE TITLE
`anoma ledger` should exit with a nonzero exit code on errors

### ISSUE THREAD

**Issue by ruuda** [anoma/anoma#1242]
I ran `anoma ledger` v0.6.1 on `namada-cq-2.a6ebeb093671093b21`. It ran for a while, then it printed this:

```
I[2022-07-20|09:42:23.525] indexed block                                module=txindex height=34641
panic: Failed to process committed block (34642:753C54ED5AE04EB1E2E119BAA15045111A631DB55A5ADE596485EE7C4B10F44A): wrong Block.Header.AppHash.  Expected 8294B69F232CBA14FD07D15A378B86C1ABECD2BEBA107897D2402AEE033D5FB4, got 0900257A013ADE5D952B60A422AE9E2CF2297F2D92D6ECF1D38DFA711E31A507
goroutine 31 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc0000fbc00, 0x0)
        github.com/tendermint/tendermint/blockchain/v0/reactor.go:401 +0x1265
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
        github.com/tendermint/tendermint/blockchain/v0/reactor.go:110 +0x85
2022-07-20T09:42:23.535181Z  INFO anoma_apps::node::ledger: Tendermint node is no longer running.
2022-07-20T09:42:23.535201Z ERROR anoma_apps::node::ledger: Err(Tendermint(Runtime("exit status: 2")))
2022-07-20T09:42:23.535209Z  INFO anoma_apps::node::ledger: Tendermint has exited, shutting down...
2022-07-20T09:42:23.535257Z  INFO anoma_apps::node::ledger: Anoma ledger node has shut down.
```

and then it exited with a regular 0 exit code, which suggests that everything is fine, but from the logs it doesn’t look fine. It should exit with a nonzero exit code, so that e.g. systemd can mark the service as failed.

**Comment by tzemanovic** [comment]
Thanks for the report! The ledger should definitely not exit with 0. I'm gonna transfer this issue to [anoma/namada](https://github.com/anoma/anoma) repository.

The reason you're getting this error is that `v0.6.1` is not compatible with this chain (it doesn't include MASP yet, that's why it's failing on this shielded transaction), it needs to be compiled from `export NAMADA_COMMIT='f1afdffd5e43ad4bb448db7bf5bc1e23464350f7'` (see https://docs.namada.net/testnets/namada-close-quarters-testnet-1.html#chain-information).
