### ISSUE TITLE
Intermittent failure in `Client.Examples.EClient.list_unrevealed_commits`

### ISSUE THREAD

**Issue by rokopt** [anoma/anoma#1563]
While running Anoma tests in a loop trying to reproduce a different bug (#1555 ), I encountered the following failure on the 114th iteration:

```
==> anoma_client
Running ExUnit with seed: 946462, max_cases: 48

...

  1) test example Anoma.Client.Examples.EClient.list_unrevealed_commits/0 (Anoma.ClientTest)
     apps/anoma_client/test/client_test.exs:4
     ** (ArgumentError) errors were found at the given arguments:

       * 1st argument: the table identifier does not refer to an existing ETS table

     code: use TestHelper.GenerateExampleTests,
     stacktrace:
       (stdlib 6.1) :ets.insert(:enode_table, {#PID<0.2706.0>, %Anoma.Node.Examples.ENode{grpc_port: 41081, tcp_ports: [], pid: #PID<0.2706.0>, node_id: "97107139"}})
       (anoma_node 0.25.0) lib/examples/e_node.ex:84: Anoma.Node.Examples.ENode.start_node/1
       (anoma_client 0.1.0) lib/examples/e_client.ex:91: Anoma.Client.Examples.EClient.create_example_client/0
       (anoma_client 0.1.0) lib/examples/e_client.ex:103: Anoma.Client.Examples.EClient.create_example_connection/0
       (anoma_client 0.1.0) lib/examples/e_client.ex:168: Anoma.Client.Examples.EClient.list_unrevealed_commits/0
       test/client_test.exs:4: (test)

................
Finished in 5.5 seconds (0.00s async, 5.5s sync)
20 tests, 1 failure
```

It's not deterministic with respect to seed (forcing the same seed doesn't make it happen reliably); it just takes running it a bunch of times, as far as I know yet.  I haven't yet delved into what the cause might be.

**Comment by agureev** [comment]
@m1dnight seems like an error we encountered based on how many nodes were started. Do you recall? If so, did we get it solved?

**Comment by murisi** [comment]
The function `Client.Examples.EClient.list_unrevealed_commits` no longer seems to exist. A simple grep for `list_unrevealed_commits` returns no results. Looking through the Git history, it seems to have been removed in https://github.com/anoma/anoma/commit/aab8364499a7e02a52222fc9a2bcb5d2905586f8 . Unless it was reintroduced under a different name, I think we can probably close this issue for now.
